name: xstore_mobile
description: XStore Mobile's client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/product/icon.png"
  image_path_android: "lib/product/icon.png"

flutter:

  uses-material-design: true

  assets:
    - lib/product/icon.png
